---
- name: Copy the Node Exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: Create textfile collector dir
  file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ _node_exporter_system_user }}"
    group: "{{ _node_exporter_system_group }}"
    recurse: true
    mode: 0775
  when: node_exporter_textfile_dir | length > 0
